---
- name: Allow all access to tcp port configured for keep-client
  become: yes
  ufw:
    rule: allow
    port: "{{ keep_client.port.local }}"
    proto: tcp

- name: Allow all access to tcp port configured for keep-ecdsa
  become: yes
  ufw:
    rule: allow
    port: "{{ keep_ecdsa.port.local }}"
    proto: tcp