---
- name: Overwrite Logstash configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-beats-input.conf
    - 20-keep-filter.conf
    - 30-elasticsearch-output.conf
  notify: restart logstash