---
- name: Pull keep-ecdsa-client Docker image
  become: yes
  docker_image:
    name: "keepnetwork/keep-ecdsa-client:{{ docker.keep_ecdsa_version }}"
    source: pull

- name: Create keep-ecdsa directories if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
  with_items:
    - "{{ '/home/{0}/keep-ecdsa'.format(ansible_ssh_user) }}"
    - "{{ '/home/{0}/keep-ecdsa/config'.format(ansible_ssh_user) }}"
    - "{{ '/home/{0}/keep-ecdsa/keystore'.format(ansible_ssh_user) }}"
    - "{{ '/home/{0}/keep-ecdsa/persistence'.format(ansible_ssh_user) }}"

- name: Deploy keep-ecdsa config
  template:
    owner: "{{ ansible_ssh_user }}"
    src: config.toml.jn2
    dest: "{{ '/home/{0}/keep-ecdsa/config/config.toml'.format(ansible_ssh_user) }}"

- name: Deploy keep_wallet.json for keep-ecdsa
  copy:
    owner: "{{ ansible_ssh_user }}"
    src: "{{ wallet }}"
    dest: "{{ '/home/{0}/keep-ecdsa/keystore/keep_wallet.json'.format(ansible_ssh_user) }}"